//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4984
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace URLSchemeViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("URLSchemeViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] ASL {
            get {
                object obj = ResourceManager.GetObject("ASL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CFNetwork {
            get {
                object obj = ResourceManager.GetObject("CFNetwork", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CoreFoundation {
            get {
                object obj = ResourceManager.GetObject("CoreFoundation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Foundation {
            get {
                object obj = ResourceManager.GetObject("Foundation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] icudt46 {
            get {
                object obj = ResourceManager.GetObject("icudt46", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] libdispatch {
            get {
                object obj = ResourceManager.GetObject("libdispatch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] libicuin {
            get {
                object obj = ResourceManager.GetObject("libicuin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] libicuuc {
            get {
                object obj = ResourceManager.GetObject("libicuuc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] libtidy {
            get {
                object obj = ResourceManager.GetObject("libtidy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] libxml2 {
            get {
                object obj = ResourceManager.GetObject("libxml2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] objc {
            get {
                object obj = ResourceManager.GetObject("objc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] plutil {
            get {
                object obj = ResourceManager.GetObject("plutil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pthreadVC2 {
            get {
                object obj = ResourceManager.GetObject("pthreadVC2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SQLite3 {
            get {
                object obj = ResourceManager.GetObject("SQLite3", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
